spring:
  application:
    name: eureka-client-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j10c201.p.ssafy.io:3307/mancity?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari:
      username: ssafy
      password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    data:
      web:
        pageable:
          one-indexed-parameters: true

server:
  port: 8081
  servlet:
    contextPath: /
  servlet.encoding:
    charset: UTF-8
    enabled: true
    force: true
  java:
    options:
      - "-Dfile.encoding=UTF-8"
      - "-Dconsole.encoding=UTF-8"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j10c201.p.ssafy.io:8761/eureka #Eureka Server ??
  instance:
    hostname: j10c201.p.ssafy.io

build:
  date: '@build.date@'

#springdoc:
#  api-docs:
#    path: /user-service/v3/api-docs
#  swagger-ui:
#    path: /user-service/swagger-ui.html
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    #path: /api/mail/v3/api-docs
    # 게이트웨이 라우팅에서 prefix를 제거하지 않았다면 해당 설정을 추가
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
openapi:
  service:
    url: http://j10c201.p.ssafy.io:8000
