server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j10c201.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: eureka-client-user
          uri: lb://EUREKA-CLIENT-USER
          predicates:
            - Path=/api/user/**
        - id: user-service-swagger
          uri: lb://EUREKA-CLIENT-USER
          predicates:
            - Path=/user-service/**
        - id: eureka-client-social
          uri: lb://EUREKA-CLIENT-SOCIAL
          predicates:
            - Path=/api/social/**
        - id: eureka-client-social
          uri: lb://EUREKA-CLIENT-SOCIAL
          predicates:
            - Path=/social-service/**
        - id: eureka-client-calc
          uri: lb://EUREKA-CLIENT-CALC
          predicates:
            - Path=/api/calc/**
        - id: eureka-client-calc
          uri: lb://EUREKA-CLIENT-CALC
          predicates:
            - Path=/calc-service/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials 
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'https://xxxxxxxxxx'
            allow-credentials: true
            allowedHeaders: '*'
            exposedHeaders: '*'
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
              - OPTIONS

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /user-service/swagger-ui/index.html
        name: User
      - url: /social-service/swagger-ui/index.html
        name: Social
      - url: /calc-service/swagger-ui/index.html
        name: Calc
    use-root-path: true
