server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j10c201.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: eureka-client-user
          uri: lb://EUREKA-CLIENT-USER
          predicates:
            - Path=/api/user/**
        - id: eureka-client-social
          uri: lb://EUREKA-CLIENT-SOCIAL
          predicates:
            - Path=/api/social/**
        - id: eureka-client-calc
          uri: lb://EUREKA-CLIENT-CALC
          predicates:
            - Path=/api/calc/**
        - id: openapi
          uri: http://j10c201.p.ssafy.io:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls[0]:
      name: User 서비스
      url: http://j10c201.p.ssafy.io:8081/swagger-ui.html
    urls[1]:
      name: Social 서비스
      url: http://j10c201.p.ssafy.io:8082/api/social/v3/api-docs
    urls[2]:
      name: Calc 서비스
      url: http://j10c201.p.ssafy.io:8083/api/calc/v3/api-docs
    use-root-path: true
