server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false #eureka server? registry? ???? ??
    fetch-registry: false       #registry? ?? ???? ???? ??
    service-url:
      defaultZone: http://j10c201.p.ssafy.io:8761/eureka